version: '3.2'
#
### Services
#
services:
#
# GMAIL
#
      relay:
        image: fametec/postfix:gmail
        restart: unless-stopped
        volumes:
         - postfix-volume:/var/spool/postfix
        ports:
         - "30025:25"
        environment:
         RELAY_USER: <put-username-here>
         RELAY_PASS: <put-password-here>
#
### Volumes
#
volumes:
      postfix-volume:
